name: dramabox_free
description: "Ứng dụng xem phim ngắn DramaBox và NetShort."
publish_to: "none"
version: 1.0.0+7

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  equatable: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  video_player: ^2.10.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  path_provider: ^2.1.5
  cached_video_player_plus: ^4.1.0
  wakelock_plus: ^1.4.0
  shorebird_code_push: ^1.1.2
  bloc_concurrency: ^0.3.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - shorebird.yaml
    - assets/icons/
